# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"
branches:
  only:
    - master
    - stable
git:
  sparse_checkout: skip-worktree-map-file
  autocrlf: input
  symlinks: true  
  

